[package]
name = "encorebaremetal"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.5"
flate2 = "1.0"
tar = "0.4"
walkdir = "2.3"